  # test-frontend:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     # Checkout code from git
  #     -checkout
  #     # Restore from cache
  #     - restore_cache:
  #         keys: [frontend-build]
      
  #     # Your job code here
  #     - run:
  #       name: Run frontend test
  #       command: |
  #         cd frontend
  #         npm install
  #         npm run test
  
  
  
    # test-backend:
  #   docker:
  #     - image: circleci/node:13.8.0
      
  #   steps:
  #     # Checkout code from git
  #     -checkout
  #     # Restore from cache
  #     - restore_cache:
  #         keys: [backend-build]        
      
  #     # Your job code here
  #     - run:
  #       name: Run backend test
  #       command: |
  #         cd backend
  #         npm install
  #         npm run test